# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\adria\OneDrive\Documents\psoc\Control_delocidad_direccion_motorDC_180V\Control_delocidad_direccion_motorDC_180V.cydsn\Control_delocidad_direccion_motorDC_180V.cyprj
# Date: Thu, 14 Sep 2023 23:07:18 GMT
#set_units -time ns
create_clock -name {LED_VELOCIDAD_ClkInternal(routed)} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 481 961} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {LED_VELOCIDAD_ClkInternal} -source [get_pins {ClockBlock/clk_sync}] -edges {1 24001 48001} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 160001 320001} -nominal_period 6666666.666666666 [list [get_pins {ClockBlock/dclk_glb_2}]]


# Component constraints for C:\Users\adria\OneDrive\Documents\psoc\Control_delocidad_direccion_motorDC_180V\Control_delocidad_direccion_motorDC_180V.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\adria\OneDrive\Documents\psoc\Control_delocidad_direccion_motorDC_180V\Control_delocidad_direccion_motorDC_180V.cydsn\Control_delocidad_direccion_motorDC_180V.cyprj
# Date: Thu, 14 Sep 2023 23:07:12 GMT
