/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Seg_aliases.h"
#include "Com_aliases.h"
#include "LED_VELOCIDAD.h"
#include "Driver_RELAY.h"
#include "Control_manual.h"
#include "PWM_Mosfet.h"
#include "MOSFET_aliases.h"
#include "MOSFET.h"
#include "isr.h"
#include "BOTONES_aliases.h"
#include "EN_A_aliases.h"
#include "EN_A.h"
#include "A1_aliases.h"
#include "A1.h"
#include "A2_aliases.h"
#include "A2.h"
#include "Clock_1.h"
#include "Clock_2.h"
#include "LED_VELOCIDAD_ClkInternal.h"
#include "LED_VELOCIDAD_Seg_Driver_L.h"
#include "LED_VELOCIDAD_Com_Driver.h"
#include "LED_VELOCIDAD_DMA_Com_dma.h"
#include "LED_VELOCIDAD_DMA_Seg_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

