/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CERO_0_aliases.h"
#include "CERO_0.h"
#include "clock.h"
#include "contador_0.h"
#include "Actuadores.h"
#include "Actuador_1_aliases.h"
#include "Actuador_1.h"
#include "contador_1.h"
#include "CERO_1_aliases.h"
#include "CERO_1.h"
#include "Actuador_0_aliases.h"
#include "Actuador_0.h"
#include "interfaz.h"
#include "UART.h"
#include "sensado.h"
#include "Sampling.h"
#include "timer_clock.h"
#include "SCRA_0_aliases.h"
#include "SCRA_0.h"
#include "SCRB_0_aliases.h"
#include "SCRB_0.h"
#include "OFF_LINEA_0_aliases.h"
#include "OFF_LINEA_0.h"
#include "Linea_0_aliases.h"
#include "SCRA_2_aliases.h"
#include "SCRA_2.h"
#include "SCRB_2_aliases.h"
#include "SCRB_2.h"
#include "OFF_LINEA_2_aliases.h"
#include "OFF_LINEA_2.h"
#include "Linea_2_aliases.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "Chipselect_aliases.h"
#include "Chipselect.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "UART_IntClock.h"
#include "SPIM_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

