/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "Clock_1.h"
#include "CEROS_aliases.h"
#include "CEROS.h"
#include "Counter.h"
#include "PWM.h"
#include "D4_aliases.h"
#include "D4.h"
#include "Ventilador_aliases.h"
#include "Ventilador.h"
#include "LCD.h"
#include "Disparador_aliases.h"
#include "Disparador.h"
#include "UART.h"
#include "wifi.h"
#include "I2C_Sensores.h"
#include "I2C_Sensores_PVT.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "D5_aliases.h"
#include "D5.h"
#include "D6_aliases.h"
#include "D6.h"
#include "D7_aliases.h"
#include "D7.h"
#include "E_aliases.h"
#include "E.h"
#include "RS_aliases.h"
#include "RS.h"
#include "Clock_2.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

