/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "num_Unidades_Decenas.h"
#include "isr_2.h"
#include "isr_1.h"
#include "num_Centenas_MIllar.h"
#include "Clock_1.h"
#include "Dis1_aliases.h"
#include "Dis1.h"
#include "Dis2_aliases.h"
#include "Dis2.h"
#include "Dis3_aliases.h"
#include "Dis3.h"
#include "Dis0_aliases.h"
#include "Dis0.h"
#include "Seg_0_aliases.h"
#include "Seg_0.h"
#include "Seg_1_aliases.h"
#include "Seg_1.h"
#include "Seg_2_aliases.h"
#include "Seg_2.h"
#include "Seg_3_aliases.h"
#include "Seg_3.h"
#include "Seg_4_aliases.h"
#include "Seg_4.h"
#include "Seg_5_aliases.h"
#include "Seg_5.h"
#include "Seg_6_aliases.h"
#include "Seg_6.h"
#include "Tog_aliases.h"
#include "Tog.h"
#include "Reset_aliases.h"
#include "Reset.h"
#include "Control_ceros.h"
#include "Clock_2.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

