/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "CERO_aliases.h"
#include "CERO.h"
#include "disparo_aliases.h"
#include "disparo.h"
#include "LCD.h"
#include "Timer.h"
#include "D4_aliases.h"
#include "D4.h"
#include "D5_aliases.h"
#include "D5.h"
#include "D6_aliases.h"
#include "D6.h"
#include "D7_aliases.h"
#include "D7.h"
#include "E_aliases.h"
#include "E.h"
#include "RS_aliases.h"
#include "RS.h"
#include "btns.h"
#include "Clock_1.h"
#include "botones_aliases.h"
#include "actualizar.h"
#include "DIS.h"
#include "DISPARADORES.h"
#include "clock.h"
#include "SCRA_1_aliases.h"
#include "SCRA_1.h"
#include "SCRB_1_aliases.h"
#include "SCRB_1.h"
#include "OFF_LINEA_1_aliases.h"
#include "OFF_LINEA_1.h"
#include "Linea_1_aliases.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

