/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SCLK_1_aliases.h"
#include "SCLK_1.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "Chipselect_aliases.h"
#include "Chipselect.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "interfaz.h"
#include "UART.h"
#include "OFF_LINEA_3_aliases.h"
#include "OFF_LINEA_3.h"
#include "SCRA_1_aliases.h"
#include "SCRA_1.h"
#include "SCRA_2_aliases.h"
#include "SCRA_2.h"
#include "SCRA_3_aliases.h"
#include "SCRA_3.h"
#include "SCRB_1_aliases.h"
#include "SCRB_1.h"
#include "SCRB_2_aliases.h"
#include "SCRB_2.h"
#include "SCRB_3_aliases.h"
#include "SCRB_3.h"
#include "OFF_LINEA_1_aliases.h"
#include "OFF_LINEA_1.h"
#include "OFF_LINEA_2_aliases.h"
#include "OFF_LINEA_2.h"
#include "Linea_3_aliases.h"
#include "Timer_0.h"
#include "timer_clock.h"
#include "DISPARADORES.h"
#include "DIS_0.h"
#include "CERO_0_aliases.h"
#include "CERO_0.h"
#include "clock.h"
#include "Timer_1.h"
#include "DIS_1.h"
#include "CERO_1_aliases.h"
#include "CERO_1.h"
#include "Timer_2.h"
#include "DIS_2.h"
#include "CERO_2_aliases.h"
#include "CERO_2.h"
#include "Linea_2_aliases.h"
#include "Linea_1_aliases.h"
#include "timer_clock_1.h"
#include "sensado.h"
#include "Sampling.h"
#include "LCD.h"
#include "D4_aliases.h"
#include "D4.h"
#include "D5_aliases.h"
#include "D5.h"
#include "D6_aliases.h"
#include "D6.h"
#include "D7_aliases.h"
#include "D7.h"
#include "E_aliases.h"
#include "E.h"
#include "RS_aliases.h"
#include "RS.h"
#include "SPIM_IntClock.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

