/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM.h"
#include "Clock_1.h"
#include "Mas_aliases.h"
#include "Mas.h"
#include "PWM_servo_aliases.h"
#include "PWM_servo.h"
#include "Reg_btn.h"
#include "Menos_aliases.h"
#include "Menos.h"
#include "Clock_2.h"
#include "Seg_aliases.h"
#include "Com_aliases.h"
#include "LED_Grados.h"
#include "LED_Grados_ClkInternal.h"
#include "LED_Grados_Seg_Driver_L.h"
#include "LED_Grados_Com_Driver.h"
#include "LED_Grados_DMA_Com_dma.h"
#include "LED_Grados_DMA_Seg_dma.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

